# Generated by Django 2.2.12 on 2020-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(default=60, max_length=60),
            preserve_default=False,
        ),
    ]
